// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Model;

namespace Server.Model.Migrations
{
    [DbContext(typeof(OnlineShop2Context))]
    partial class OnlineShop2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Server.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("PurchaseItemId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseItem_Id");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseItemId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Server.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_id");

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Server.Model.PurchaceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PurchaceItem");
                });

            modelBuilder.Entity("Server.Model.Order", b =>
                {
                    b.HasOne("Server.Model.PurchaceItem", "PurchaseItem")
                        .WithMany("Orders")
                        .HasForeignKey("PurchaseItemId")
                        .HasConstraintName("FK__Orders__Purchase__47DBAE45");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("Server.Model.Product", b =>
                {
                    b.HasOne("Server.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__Categor__4222D4EF");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Server.Model.PurchaceItem", b =>
                {
                    b.HasOne("Server.Model.Product", "Product")
                        .WithMany("PurchaceItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__PurchaceI__Produ__44FF419A");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Server.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Server.Model.Product", b =>
                {
                    b.Navigation("PurchaceItems");
                });

            modelBuilder.Entity("Server.Model.PurchaceItem", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
